### ISSUE TITLE
Convert .pptx to Xaringan Slides

### ISSUE THREAD

**Issue by HanselPalencia** [nhs-r-community/intro_rmd#3]

**Comment by servindc** [comment]
Hi. Maybe I could help with this issue.

**Comment by ChrisBeeley** [comment]
That would be great, thanks 🙏

**Comment by HanselPalencia** [comment]
Hi @ServinDC, let's link up on this as I'm delivering this workshop next month. Maybe it's something we can work on together in preparation?

Let me know what you think!

**Comment by servindc** [comment]
Hi @HanselPalencia. Sure, sounds good to me.

**Comment by servindc** [comment]
Hi there.

I have a working Rmd file for the xaringan version of the presentation, inside the [slides/ folder of my fork](https://github.com/ServinDC/intro_rmd-3/tree/main/slides), with a similar style as the original. It only needs the `style.css` file and the `imgs/` folder, both included in `slides/`.
I was hoping if you could check it for any changes, errors  or suggestions, before making the pull request.

**Comment by HanselPalencia** [comment]
I noticed some issues with the Rmd file, mostly things that needed to be corrected in my original slides.

One is that the YAML - Yet Another Markdown Langugage should actually be Yet Another Markup Langauge

The Parameterized rmarkdown section also seems to be duplicated.

Once this has been corrected I can pull.

@ServinDC

**Comment by servindc** [comment]
The YAML acronym description is corrected.

The original 'Parameterized rmarkdown' slide had two images so I divided it into two slides in the Rmd to include one of its two images in each new slide, but I can put both images in the same slide to match the original. Let me know which case would be better.

@HanselPalencia

**Comment by HanselPalencia** [comment]
Lets leave it how it is and we can change later depending on how it feels when flipping through it.
